language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: nodejs-shareyourideas
  api_key:
    secure: hAMxXZPkWMZSEpj3ORU2SLW3yQQj6ARsv4spOWnCzHKz0as7Taeigl9eiuxsaASXv6md6RAPChHhv/ayDzyX8i97d8z8KnNQVCHNiFHVymKKFY8xi8rzoAYyUYg2SpMtGY+N30Q+0WwIRO0zfO7X+0MM4MZn9lrXEyUZjpV8bzsLnDMR7+g+Hv7PpTxFtRMu/14uJJfNuZ4nfpCrwZ59HQW4CclHCkHnaeug1dB7LJ3JIRJCP2Ru2ITNNepTlVe6vaTEvOASKEz7cOv4HiXLLq8nvxbwFQCF6bUnPLsD+IQ8ZfgmGAhUBEj8e2oyXxpLUKCvV1xVts92W8Ye26zieFrHaR73ETyrY1wwO7u/Eo1NdkXxOgoCcWmFTUWh018xJnDBNFYTomhum6X8nF022Nsz0Fb3N9+o0rAj4mFs2/a/ZX4XKKVbPFM97SDfYN0wZizcfsjuXOPUibbM/le7qHcLFmYrd3beUGZNeHKDc7cwjCAi/g+3eQZJxH6k4nWKIAHmi5y2pNJ1d8+eaYgfCzDD8mPLTO159y950ggxkjaWTCzXu29t8OtQ3ukzQ4nl4THXw9Di5AhLOT0hV31yhBo5xWX6LupXpWhkyOS/feX8LjZpDfAGXCzni52n5WUJC2w2Ic8qE0BGh6kKdAXFpeTMOifCNbA6dG+Xr41cqj4=
